#!/bin/bash

source ../model_functions.sh

set -x

sim="$1"
paramset="$2"

# Set model variables and paths:
#   model, model_impl, model_outdir, model_params,
#   model_output_default, model_ref_default, model_generate_default
model_setup "$sim" "$paramset"

"$model_impl" "$model_output_default" $model_params

if [ ! -r "$model_ref_default" ]; then
    [ -x "$model_generate_default" ] || die "unable to find reference data generation script"
    "$model_generate_default" "$model_ref_default" $model_params
fi

./comparex "$model_output_default" --ref "$model_ref_default" -o "$model_outdir/delta.n4"

# Not implemented yet:
#./threshold_test "$outdir/linf.n4" "v.abserr.lb<1e-6" > "$outdir/status"
