#!/usr/bin/env bash
# Invocation: run outputdir simname paramsetname

# Change to script directory and attempt to find nsuite base directory.

unset CDPATH
cd "${BASH_SOURCE[0]%/*}"
[ -n "$ns_base_path" ] || ns_base_path="$(cd ../..; pwd)"

# Set up model paths, model_XXX variables, and functions
# exit_model_fail, exit_model_missing.

outdir=$1
shift

source "$ns_base_path/scripts/model_common.sh"
model_setup rc-expsyn "$@"

# Run sim-specific implementation with parameter data.

impl="./run-$model_sim"
[ -x "$impl" ] || exit_model_missing

outfile="$outdir/run.nc"
"$impl" "$outfile" $model_param_data || exit 1

# Generate reference data if required.

reffile=$(model_find_cacheable "ref-${model_name}-${model_param}.nc") || \
    ./generate-rc-expsyn "$reffile" $model_param_data || exit 1

# Run comparison.

deltafile="$outdir/delta.nc"
comparex "$outfile" --warn --ref "$reffile" --interpolate time -o "$deltafile" || exit 1

thresholdx "$deltafile" -e "voltage.relerr.lb<0.01" || exit_model_fail
