#!/usr/bin/env bash
# Invocation: run outputdir simname paramsetname

# Change to script directory and attempt to find nsuite base directory.

unset CDPATH
cd "${BASH_SOURCE[0]%/*}"
[ -n "$ns_base_path" ] || ns_base_path="$(cd ../..; pwd)"

# Set up model paths,  model_XXX variables, and functions
# exit_model_fail, exit_model_missing.

outdir=$1
shift

source "$ns_base_path/scripts/model_common.sh"
model_setup rc-exp2syn-spike "$@"

# Run sim-specific model with parameter data.
#
# Expected output variables:
#     v0      voltage trace of cell 0 soma (dimension 'time')
#     spike   time to first spike on cell (dimension 'gid')
#
# For CoreNEURON, voltage traces will be omitted; the pass/fail
# test only looks at spike time differences.

impl="./run-$model_sim"
[ -x "$impl" ] || exit_model_missing

outfile="$outdir/run.nc"
"$impl" "$outfile" $model_param_data || exit 1

# Generate reference data if required.

reffile=$(model_find_cacheable "ref-${model_name}-${model_param}.nc") || \
    ./generate-rc-exp2syn-spike "$reffile" $model_param_data || exit 1

# Run comparison.

deltafile="$outdir/delta.nc"
comparex "$outfile" --warn --ref "$reffile" --var spike -o "$deltafile" || exit 1

# Get threshold from parameter data 'max_error'

max_error=
for param in $model_param_data; do
    if [[ "$param" =~ ^'max_error='(.*) ]]; then
        max_error=${BASH_REMATCH[1]}
    fi
done
if [ -z "$max_error" ]; then
    echo 'Missing max_error in parameter set' >&2
    exit 1
fi

thresholdx "$deltafile" -e "spike.abserr<$max_error" || exit_model_fail
