name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testallconfigs:
    name: "Tests across OSes, versions, compilers, and build configs."
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name:  "Linux Min GCC",
            os:    "ubuntu-20.04",
            cc:    "gcc-10",
            cxx:   "g++-10",
            cmake: "3.22.x",
          }
    env:
        CC:         ${{ matrix.config.cc }}
        CXX:        ${{ matrix.config.cxx }}
    steps:
      - name: "Linux: get clang/gcc, libxml2"
        if: ${{ startsWith(matrix.config.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-10
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: ${{ matrix.config.cmake }}
      - name: Clone
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install
        run: |
           ./install-local.sh arbor --env=systems/gh.sh
      - name: Run
        run: |
          ./run-bench.sh arbor --config=small
